CREATE OR REPLACE PROCEDURE `<PROJECT_ID>.DATAPROC.SP1`()
BEGIN
  CREATE OR REPLACE TABLE `<PROJECT_ID>.DATAPROC.test_sp1` AS
  SELECT * FROM `<PROJECT_ID>.DATAPROC.test`;
END;


CREATE OR REPLACE PROCEDURE `<PROJECT_ID>.DATAPROC.SP2`()
BEGIN
  CREATE OR REPLACE TABLE `<PROJECT_ID>.DATAPROC.test_sp2` AS
  SELECT * FROM `<PROJECT_ID>.DATAPROC.test`;
END;

CREATE OR REPLACE PROCEDURE `<PROJECT_ID>.DATAPROC.SP3`()
BEGIN
  CREATE OR REPLACE TABLE `<PROJECT_ID>.DATAPROC.test_sp3` AS (
    SELECT * FROM `<PROJECT_ID>.DATAPROC.test_sp1`
    UNION ALL
    SELECT * FROM `<PROJECT_ID>.DATAPROC.test_sp2`
  );
END;
